# Generated by Django 4.2.10 on 2025-02-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newssection",
            name="sources",
            field=models.TextField(
                help_text="Enter URLs separated by commas, newlines, or spaces"
            ),
        ),
    ]
