# Generated by Django 4.2.10 on 2025-02-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0002_alter_newssection_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("sources", models.TextField()),
                ("confidence", models.CharField(default="medium", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="news_app.newssection",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="news_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
