# Generated by Django 4.2.10 on 2025-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0003_newsitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newssection",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="newssection",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order in which the section appears"
            ),
        ),
    ]
