# Generated by Django 4.2.10 on 2025-12-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_newssection_options_newssection_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('content_length', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['domain'], name='news_app_fe_domain_49f6fb_idx'), models.Index(fields=['timestamp'], name='news_app_fe_timesta_dc7e2a_idx'), models.Index(fields=['status'], name='news_app_fe_status_f9cccf_idx')],
            },
        ),
    ]
